#!/bin/bash

MENU_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source $MENU_DIR/lib/menu_helpers.sh

MUSIC_DIR="${HOME}/docs/music"
CACHE_FILE="/tmp/mpcmenu_cache"

tempOut=$(mpc --format "")

# playState=$(echo "${tempOut}" | sed -n 2p | awk '{ print $1; }')

stateLine=$(echo "${tempOut}" | sed 's/volume://')
randomState=$(awk '/repeat:/{ print $5; }' <<< "${stateLine}")
repeatState=$(awk '/repeat:/{ print $3; }' <<< "${stateLine}")
singleState=$(awk '/repeat:/{ print $7; }' <<< "${stateLine}")
consumeState=$(awk '/repeat:/{ print $9; }' <<< "${stateLine}")

# Menu Items
mainMenu="[select]
[push-dir]
[push-loop]
[current]
[play]
[stop]
[pause]
[load]
[playlist]
[clear]
[previous]
[next]
[seek]
[replay]
[random: ${randomState}]
[repeat: ${repeatState}]
[single: ${singleState}]
[consume: ${consumeState}]
[lyrics]
[rescan]"

playlistOptions="[add-all]
[remove]
[clear]
[save]
[load]
[delete]"

seekOptions="0%
10%
20%
30%
40%
50%
60%
70%
80%
90%"

filterOptions="any
artist
album
title
track
name
genre
date
composer
performer
comment
disc
filename"

action=$(menu "Option: " "${mainMenu}")
case "${action}" in
    '[select]')
        candidates=$(mpc playlist --format '%position%  [%album% - ][%artist% - ]%title%')
        selection=$(menu "Song: " "${candidates}")

        # Only select song if not in consume ("playback queue") mode.
        if [[ "${consumeState}" != "on" ]]; then
            if [[ -n "${selection}" ]]; then
                songNum=$(awk '{print $1}' <<< "${selection}")
                mpc -q play "${songNum}"
            fi
        fi
        ;;
    '[push-dir]')
        pushd ${MUSIC_DIR} > /dev/null
        musicDirList=$(find . -type d | sed -e 's!^\./!!')
        popd > /dev/null
        query=$(menu "Add: " "${musicDirList}")

        if [[ -n "${query}" ]]; then
            mpc ls "${query}" | mpc -q add
        fi
        ;;
    '[push-loop]')
        # if [[ ! -a "${CACHE_FILE}" || "${CACHE_FILE}" -ot "${MUSIC_DIR}" ]]; then
        #     notify-send "MPD:" "Building Cache"
        #     musicList=$(mpc listall | tee "${CACHE_FILE}")
        # else
        #     notify-send 'MPD:' 'Using Cache'
        #     musicList=$(<${CACHE_FILE})
        # fi

        filterType=$(menu "Filter Type: " "${filterOptions}")
        [[ -z "${filterType}" ]] && exit

        filterQuery=$(menu "Query (${filterType}): " "")

        # We should permit empty query strings so we can sift through all
        # elements of a filter type.

        # [[ -z "${filterQuery}" ]] && exit

        filterList=$(mpc search "${filterType}" "${filterQuery}")

        count=0
        selection="a"
        while [[ -n "${selection}" ]]; do
            selection=$(menu "Song ($count): " "${filterList}")
            echo " ${selection}"
            if [[ -n "${selection}" ]]; then
                mpc -q add "${selection}"
                ((count++))
            fi
        done
        ;;
    '[current]')
        songInfo=$(mpc -f 'Title:  [%title%]\nArtist: [%artist%]\nAlbum:  [%album%]\n ')
        notify-send "MPD:" "${songInfo}"
        ;;
    '[play]')
        mpc -q toggle
        ;;
    '[stop]')
        mpc -q stop
        ;;
    '[pause]')
        mpc -q toggle
        ;;
    '[load]')
        choice=$(menu "Load: " "$(mpc lsplaylists)")
        if [[ -n "${choice}" ]]; then
            mpc -q stop
            mpc -q clear
            mpc -q load "${choice}"
            notify-send "MPD:" "Playlist \"${choice}\" Loaded"
        fi
        ;;
    '[playlist]')
        action=$(menu "Option: " "${playlistOptions}")
        case "${action}" in
            '[add-all]')
                mpc -q update
                mpc ls | mpc -q add
                ;;
            '[remove]')
                selection="a"
                while [[ -n "${selection}" ]]; do
                    candidates=$(mpc playlist --format '%position%  [%album% - ][%artist% - ]%title%')
                    selection=$(menu "Song: " "${candidates}")

                    if [[ -n "${selection}" ]]; then
                        songNum=$(awk '{print $1}' <<< "${selection}")
                        mpc -q del "${songNum}"
                    fi
                done
            ;;
            '[clear]')
                mpc -q clear
                notify-send "MPD:" "Playlist Cleared"
                ;;
            '[load]')
                choice=$(menu "Load: " "$(mpc lsplaylists)")
                if [[ -n "${choice}" ]]; then
                    mpc -q stop
                    mpc -q clear
                    mpc -q load "${choice}"
                    notify-send "MPD:" "Playlist \"${choice}\" Loaded"
                fi
                ;;
            '[save]')
                name=$(menu "Load: " "$(mpc lsplaylists)")
                if [[ -n "${name}" ]]; then
                    mpc save "${name}"
                    notify-send "MPD:" "Playlist \"${name}\" Saved"
                fi
                ;;
            '[delete]')
                name=$(menu "Load: " "$(mpc lsplaylists)")
                if [[ -n "${name}" ]]; then
                    mpc rm "${name}"
                    notify-send "MPD:" "Playlist \"${name}\" Deleted"
                fi
                ;;
        esac
        ;;
    '[clear]')
        mpc -q clear
        notify-send "MPD:" "Playlist Cleared"
        ;;
    '[previous]')
        mpc -q prev
        ;;
    '[next]')
        mpc -q next
        ;;
    '[seek]')
        seek=$(menu "Seek: " "${seekOptions}")
        if [[ -n "${seek}" ]]; then
            mpc -q seek "${seek}"
        fi
        ;;
    '[replay]')
        mpc -q stop
        mpc -q play
        ;;
    '[Random'*)
        mpc -q random
        ;;
    '[Repeat'*)
        mpc -q repeat
        ;;
    '[Single'*)
        mpc -q single
        ;;
    '[Consume'*)
        mpc -q consume
        ;;
    '[lyrics]')
        song=$(mpc current)
        lyricsFile="$HOME/.lyrics/${song}.txt"

        if [[ -e "${lyricsFile}" ]]; then
            if [[ "${BACKEND}" == "fzf" ]]; then
                ${EDITOR:-gvim} "${lyricsFile}"
            else
                xdg-open "${lyricsFile}"
            fi
            # emacsclient --no-wait "${lyricsFile}" 2> /dev/null
        else
            notify-send "MPD:" "Lyrics for \"${song}\" not found"
            createFlag=$(confirm "Create Lyrics File?")
            if [[ "${createFlag,,}" == "yes" ]]; then
                touch "${lyricsFile}"
                notify-send "MPD:" "Created ${lyricsFile}"
            fi
        fi
        ;;
    '[rescan]')
        notify-send "MPD Database" "Updating"
        mpc -q update
        ;;
esac
